language: cpp

dist: bionic

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"

sudo: required

before_install:
    - ./travis_install_capstone.sh

before_script:
    - mkdir build && cd build && cmake ..

script:
    - make

os:
    - linux

addons:
    apt:
        packages:
            - build-essential
            - cmake
            - libcapstone-dev
            - libgraphviz-dev
            - libqt5svg5-dev
            - libqt5xmlpatterns5-dev
            - pkg-config
            - qt5-default
            - qtbase5-dev
